version: '3'

vars:
  LOGO_SIZES: |
    16
    19
    32
    38
    48
    64
    96
    128
    256
    512

tasks:
  default:
   extension:build:
    deps:
      - extension:build

  icons:export:
    cmds:
      - |
        {{ range $i, $logo_size := .LOGO_SIZES | splitLines -}}
          {{- if $logo_size -}}
            npx svgexport icons/logo.svg icons/logo-{{ . }}.png {{ . }}:{{ . }}
          {{- end }}
        {{ end -}}
    sources:
      - icons/*.svg
    generates:
      - icons/*.png

  extension:build:
    desc: Build WebExtension (both v2 and v3 manifests)
    deps:
      - extension:v2:build
      - extension:v3:build

  extension:stage:
    deps:
      - icons:export
    cmds:
      - rm -rf build/{{ .manifest_version }}
      - mkdir -p build/{{ .manifest_version }}/icons
      - cp manifest_{{ .manifest_version }}.json build/{{ .manifest_version }}/manifest.json
      - cp icons/*.png build/{{ .manifest_version }}/icons
      - cp -r _locales popup build/{{ .manifest_version }}
    sources:
      - _locales/*
      - manifest_{{ .manifest_version }}.json
      - icons/*.png
      - popup/*
    generates:
      - build/{{ .manifest_version }}

  extension:v2:build:
    cmds:
      - task: extension:stage
        vars:
          manifest_version: v2
      - cd build/v2 && npx web-ext build --overwrite-dest
    sources:
      - manifest_v2.json
      - icons/*.png
      - popup/*
    generates:
      - build/v2/web-ext-artifacts/multi-tab-*.zip
  extension:v3:build:
    cmds:
      - task: extension:stage
        vars:
          manifest_version: v3
      - cd build/v3 && npx web-ext build --overwrite-dest
    sources:
      - manifest_v3.json
      - icons/*.png
      - popup/*
    generates:
      - build/v3/web-ext-artifacts/multi-tab-*.zip

  run:chrome:
    desc: Launch Chrome with the extension loaded
    cmds:
      - cd build/v3 && node ../../task/run-chrome.js
  run:firefox:
    desc: Launch Firefox with the extension loaded
    cmds:
      - cd build/v2 && npx web-ext run --firefox=firefox --browser-console
