version: '3'

tasks:
  default:
    deps:
      - extension:v2:build
      - extension:v3:build

  icons:export:
    cmds:
      - npx svgexport icons/logo.svg icons/logo-48.png 48:48
      - npx svgexport icons/logo.svg icons/logo-96.png 96:96
    sources:
      - icons/*.svg
    generates:
      - icons/*.png

  extension:stage:
    deps:
      - icons:export
    cmds:
      - rm -rf build/{{ .manifest_version }}
      - mkdir -p build/{{ .manifest_version }}/icons
      - cp manifest_{{ .manifest_version }}.json build/{{ .manifest_version }}/manifest.json
      - cp icons/*.png build/{{ .manifest_version }}/icons
      - cp -r popup build/{{ .manifest_version }}/popup
    sources:
      - manifest_{{ .manifest_version }}.json
      - icons/*.png
      - popup/*
    generates:
      - build/{{ .manifest_version }}

  extension:v2:build:
    cmds:
      - task: extension:stage
        vars:
          manifest_version: v2
      - cd build/v2 && npx web-ext build --overwrite-dest
    sources:
      - manifest_v2.json
      - icons/*.png
      - popup/*
    generates:
      - build/v2/web-ext-artifacts/multi-tab-*.zip
  extension:v3:build:
    cmds:
      - task: extension:stage
        vars:
          manifest_version: v3
      - cd build/v3 && npx web-ext build --overwrite-dest
    sources:
      - manifest_v3.json
      - icons/*.png
      - popup/*
    generates:
      - build/v3/web-ext-artifacts/multi-tab-*.zip

  run:chrome:
    cmds:
      - cd build/v3 && node ../../task/run-chrome.js
  run:firefox:
    cmds:
      - cd build/v2 && npx web-ext run --firefox=firefox --browser-console
