version: '3'

tasks:
  default:
   extension:build:
    deps:
      - extension:build

  icons:export:
    cmds:
      - npx svgexport icons/logo.svg icons/logo-16.png 16:16
      - npx svgexport icons/logo.svg icons/logo-19.png 19:19
      - npx svgexport icons/logo.svg icons/logo-32.png 32:32
      - npx svgexport icons/logo.svg icons/logo-38.png 38:38
      - npx svgexport icons/logo.svg icons/logo-48.png 48:48
      - npx svgexport icons/logo.svg icons/logo-64.png 64:64
      - npx svgexport icons/logo.svg icons/logo-96.png 96:96
      - npx svgexport icons/logo.svg icons/logo-128.png 128:128
      - npx svgexport icons/logo.svg icons/logo-256.png 256:256
      - npx svgexport icons/logo.svg icons/logo-512.png 512:512
    sources:
      - icons/*.svg
    generates:
      - icons/*.png

  extension:build:
    desc: Build WebExtension (both v2 and v3 manifests)
    deps:
      - extension:v2:build
      - extension:v3:build

  extension:stage:
    deps:
      - icons:export
    cmds:
      - rm -rf build/{{ .manifest_version }}
      - mkdir -p build/{{ .manifest_version }}/icons
      - cp manifest_{{ .manifest_version }}.json build/{{ .manifest_version }}/manifest.json
      - cp icons/*.png build/{{ .manifest_version }}/icons
      - cp -r _locales popup build/{{ .manifest_version }}
    sources:
      - _locales/*
      - manifest_{{ .manifest_version }}.json
      - icons/*.png
      - popup/*
    generates:
      - build/{{ .manifest_version }}

  extension:v2:build:
    cmds:
      - task: extension:stage
        vars:
          manifest_version: v2
      - cd build/v2 && npx web-ext build --overwrite-dest
    sources:
      - manifest_v2.json
      - icons/*.png
      - popup/*
    generates:
      - build/v2/web-ext-artifacts/multi-tab-*.zip
  extension:v3:build:
    cmds:
      - task: extension:stage
        vars:
          manifest_version: v3
      - cd build/v3 && npx web-ext build --overwrite-dest
    sources:
      - manifest_v3.json
      - icons/*.png
      - popup/*
    generates:
      - build/v3/web-ext-artifacts/multi-tab-*.zip

  run:chrome:
    desc: Launch Chrome with the extension loaded
    cmds:
      - cd build/v3 && node ../../task/run-chrome.js
  run:firefox:
    desc: Launch Firefox with the extension loaded
    cmds:
      - cd build/v2 && npx web-ext run --firefox=firefox --browser-console
